import type {
  CompletedShift,
  DriverRow,
  MapPin,
  RevenueDay,
  VehicleRow,
} from './types'

export const DRIVERS: DriverRow[] = [
  {
    id: 'd1',
    initials: 'LM',
    firstName: 'Lucas',
    lastName: 'Maes',
    email: 'lucas.m@example.be',
    phone: '0498 12 34 56',
    city: 'Anvers',
    postcode: '2030',
    status: 'active',
    shiftStartedAt: '15:45',
    shiftDurationMinutes: 757,
    paymentEnabled: true,
    avatarHue: 220,
  },
  {
    id: 'd2',
    initials: 'YS',
    firstName: 'Youssef',
    lastName: 'Sbai',
    email: 'youssef.s@example.be',
    phone: '0476 33 22 11',
    city: 'Anvers',
    postcode: '2180',
    status: 'active',
    shiftStartedAt: '15:40',
    shiftDurationMinutes: 762,
    paymentEnabled: true,
    avatarHue: 280,
  },
  {
    id: 'd3',
    initials: 'MY',
    firstName: 'Mehmet',
    lastName: 'Yilmaz',
    email: 'mehmet.y@example.be',
    phone: '0495 88 77 66',
    city: 'Schaerbeek',
    postcode: '2030',
    status: 'active',
    shiftStartedAt: '09:28',
    shiftDurationMinutes: 1133,
    paymentEnabled: true,
    avatarHue: 20,
  },
  {
    id: 'd4',
    initials: 'BJ',
    firstName: 'Bram',
    lastName: 'Janssens',
    email: 'bram.j@example.be',
    phone: '0488 11 22 33',
    city: 'Anderlecht',
    postcode: '2170',
    status: 'active',
    shiftStartedAt: '16:29',
    shiftDurationMinutes: 712,
    paymentEnabled: true,
    avatarHue: 200,
  },
  {
    id: 'd5',
    initials: 'MB',
    firstName: 'Mohamed',
    lastName: 'Benali',
    email: 'mohamed.b@example.be',
    phone: '0470 99 88 77',
    city: 'Saint-Gilles',
    postcode: '2060',
    status: 'active',
    shiftStartedAt: '13:20',
    shiftDurationMinutes: 902,
    paymentEnabled: true,
    avatarHue: 190,
  },
  {
    id: 'd6',
    initials: 'OM',
    firstName: 'Omar',
    lastName: 'Mouss',
    email: 'omar.m@example.be',
    phone: '0466 77 11 22',
    city: 'Molenbeek',
    postcode: '2180',
    status: 'active',
    shiftStartedAt: '18:55',
    shiftDurationMinutes: 567,
    paymentEnabled: false,
    avatarHue: 110,
  },
  {
    id: 'd7',
    initials: 'BB',
    firstName: 'Bashkim',
    lastName: 'Berisha',
    email: 'bashkim.b@example.be',
    phone: '0498 65 43 21',
    city: 'Etterbeek',
    postcode: '2040',
    status: 'leave',
    shiftStartedAt: '—',
    shiftDurationMinutes: 0,
    paymentEnabled: true,
    avatarHue: 0,
  },
  {
    id: 'd8',
    initials: 'IB',
    firstName: 'Ibrahim',
    lastName: 'Belkacem',
    email: 'ibrahim.b@example.be',
    phone: '0490 22 11 88',
    city: 'Forest',
    postcode: '2600',
    status: 'active',
    shiftStartedAt: '14:18',
    shiftDurationMinutes: 843,
    paymentEnabled: true,
    avatarHue: 250,
  },
  {
    id: 'd9',
    initials: 'BA',
    firstName: 'Bassam',
    lastName: 'Al-Khoury',
    email: 'bassam.a@example.be',
    phone: '0473 44 55 66',
    city: 'Ixelles',
    postcode: '2050',
    status: 'active',
    shiftStartedAt: '15:07',
    shiftDurationMinutes: 795,
    paymentEnabled: true,
    avatarHue: 130,
  },
  {
    id: 'd10',
    initials: 'AP',
    firstName: 'Andriy',
    lastName: 'Petrenko',
    email: 'andriy.p@example.be',
    phone: '0495 77 88 99',
    city: 'Anvers',
    postcode: '2000',
    status: 'sick',
    shiftStartedAt: '—',
    shiftDurationMinutes: 0,
    paymentEnabled: true,
    avatarHue: 50,
  },
  {
    id: 'd11',
    initials: 'HM',
    firstName: 'Hassan',
    lastName: 'Marrakchi',
    email: 'hassan.m@example.be',
    phone: '0469 12 33 44',
    city: 'Laeken',
    postcode: '1020',
    status: 'active',
    shiftStartedAt: '21:13',
    shiftDurationMinutes: 408,
    paymentEnabled: true,
    avatarHue: 160,
  },
  {
    id: 'd12',
    initials: 'MR',
    firstName: 'Marco',
    lastName: 'Russo',
    email: 'marco.r@example.be',
    phone: '0478 11 99 22',
    city: 'Auderghem',
    postcode: '1160',
    status: 'active',
    shiftStartedAt: '24:52',
    shiftDurationMinutes: 210,
    paymentEnabled: true,
    avatarHue: 90,
  },
]

export const VEHICLES: VehicleRow[] = [
  {
    id: 'v1',
    plate: 'T-XJJ-888',
    model: 'Ford Puma',
    driverDay: 'Lucas Maes',
    driverNight: 'Marco Russo',
    status: 'good',
    transmission: 'auto',
  },
  {
    id: 'v2',
    plate: 'T-XGK-939',
    model: 'Toyota Prius',
    driverDay: 'Mehmet Yilmaz',
    driverNight: 'Hassan Marrakchi',
    status: 'in_service',
    transmission: 'auto',
  },
  {
    id: 'v3',
    plate: 'T-XEE-455',
    model: 'Mercedes Classe E',
    driverDay: 'Mohamed Benali',
    driverNight: null,
    status: 'maintenance',
    transmission: 'auto',
  },
  {
    id: 'v4',
    plate: 'T-XEJ-999',
    model: 'BMW Série 3',
    driverDay: 'Youssef Sbai',
    driverNight: 'Omar Mouss',
    status: 'in_service',
    transmission: 'manual',
  },
  {
    id: 'v5',
    plate: 'T-XAC-714',
    model: 'Skoda Octavia',
    driverDay: 'Bram Janssens',
    driverNight: 'Bassam Al-Khoury',
    status: 'repair',
    transmission: 'auto',
  },
  {
    id: 'v6',
    plate: 'T-XBX-223',
    model: 'Volkswagen Passat',
    driverDay: 'Ibrahim Belkacem',
    driverNight: null,
    status: 'good',
    transmission: 'auto',
  },
  {
    id: 'v7',
    plate: 'T-XCE-605',
    model: 'Renault Mégane',
    driverDay: 'Bashkim Berisha',
    driverNight: null,
    status: 'off',
    transmission: 'manual',
  },
]

export const REVENUE_BY_DAY: RevenueDay[] = [
  { label: 'L', uber: 412, bolt: 218, heetch: 95, cash: 70 },
  { label: 'M', uber: 488, bolt: 244, heetch: 110, cash: 82 },
  { label: 'M', uber: 391, bolt: 297, heetch: 88, cash: 95 },
  { label: 'J', uber: 525, bolt: 312, heetch: 142, cash: 110 },
  { label: 'V', uber: 612, bolt: 388, heetch: 180, cash: 145 },
  { label: 'S', uber: 738, bolt: 421, heetch: 215, cash: 192 },
  { label: 'D', uber: 568, bolt: 365, heetch: 168, cash: 124 },
]

export const MAP_PINS: MapPin[] = [
  { id: 'm1', initials: 'LM', lat: 28, lng: 22, status: 'on_ride', driver: 'Lucas' },
  { id: 'm2', initials: 'YS', lat: 45, lng: 38, status: 'available', driver: 'Youssef' },
  { id: 'm3', initials: 'MY', lat: 62, lng: 48, status: 'on_ride', driver: 'Mehmet' },
  { id: 'm4', initials: 'BJ', lat: 38, lng: 65, status: 'on_ride', driver: 'Bram' },
  { id: 'm5', initials: 'MB', lat: 72, lng: 31, status: 'available', driver: 'Mohamed' },
  { id: 'm6', initials: 'OM', lat: 56, lng: 78, status: 'on_ride', driver: 'Omar' },
  { id: 'm7', initials: 'BA', lat: 22, lng: 60, status: 'available', driver: 'Bassam' },
  { id: 'm8', initials: 'IB', lat: 80, lng: 56, status: 'on_ride', driver: 'Ibrahim' },
]

export const KPI = {
  driversActive: 9,
  driversTrend: '+2 cette semaine',
  vehiclesOnRoad: 5,
  vehiclesPercent: 71,
  revenueToday: 2450,
  revenueTrend: '+15% ce mois',
  driversTotal: 12,
  driversOnLeave: 1,
  driversSick: 1,
  vehiclesTotal: 7,
  vehiclesInService: 2,
  vehiclesMaintenance: 1,
  vehiclesRepair: 1,
  vehiclesGood: 2,
  vehiclesOff: 1,
}

export const SHIFT_HOURS = [
  4, 6, 5, 7, 9, 12, 16, 22, 28, 35, 42, 48, 50, 47, 41, 37, 32, 28, 25, 20, 15, 12, 9, 6,
]

// Shifts terminés aujourd'hui — 6 entrées avec une bonne diversité de profils
// (jour/nuit, courtes/longues, plus/moins rentables que la moyenne)
export const COMPLETED_SHIFTS_TODAY: CompletedShift[] = [
  {
    id: 'cs1',
    driverInitials: 'LM',
    driverName: 'Lucas Maes',
    driverHue: 220,
    vehiclePlate: 'T-XJJ-888',
    vehicleModel: 'Ford Puma',
    startedAt: '06:30',
    endedAt: '14:42',
    durationMinutes: 492,
    rides: 22,
    net: 312,
    vsAvgPercent: 18,
  },
  {
    id: 'cs2',
    driverInitials: 'YS',
    driverName: 'Youssef Sbai',
    driverHue: 280,
    vehiclePlate: 'T-XEJ-999',
    vehicleModel: 'BMW Série 3',
    startedAt: '07:12',
    endedAt: '15:08',
    durationMinutes: 476,
    rides: 19,
    net: 268,
    vsAvgPercent: 4,
  },
  {
    id: 'cs3',
    driverInitials: 'MY',
    driverName: 'Mehmet Yilmaz',
    driverHue: 20,
    vehiclePlate: 'T-XGK-939',
    vehicleModel: 'Toyota Prius',
    startedAt: '05:45',
    endedAt: '13:30',
    durationMinutes: 465,
    rides: 24,
    net: 332,
    vsAvgPercent: 26,
  },
  {
    id: 'cs4',
    driverInitials: 'MB',
    driverName: 'Mohamed Benali',
    driverHue: 190,
    vehiclePlate: 'T-XBX-223',
    vehicleModel: 'VW Passat',
    startedAt: '08:00',
    endedAt: '12:18',
    durationMinutes: 258,
    rides: 11,
    net: 138,
    vsAvgPercent: -12,
  },
  {
    id: 'cs5',
    driverInitials: 'IB',
    driverName: 'Ibrahim Belkacem',
    driverHue: 250,
    vehiclePlate: 'T-XAC-714',
    vehicleModel: 'Skoda Octavia',
    startedAt: '07:50',
    endedAt: '14:05',
    durationMinutes: 375,
    rides: 17,
    net: 222,
    vsAvgPercent: -3,
  },
  {
    id: 'cs6',
    driverInitials: 'BA',
    driverName: 'Bassam Al-Khoury',
    driverHue: 130,
    vehiclePlate: 'T-XCE-605',
    vehicleModel: 'Renault Mégane',
    startedAt: '06:00',
    endedAt: '13:48',
    durationMinutes: 468,
    rides: 21,
    net: 290,
    vsAvgPercent: 11,
  },
]

// Distribution des shifts par tranche horaire (pour la heatmap)
// 24h, valeurs 0-10 = nombre de shifts actifs simultanément à cette heure
export const SHIFT_HEATMAP = [
  2, 1, 1, 0, 0, 1, 3, 5, 6, 5, 4, 4, 5, 5, 4, 3, 4, 6, 7, 8, 7, 5, 4, 3,
]
